name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  setup-runner:
    runs-on: self-hosted  # This job runs on the self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8

    - name: Install Python with Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Set up Python
      run: |
        choco install python --version 3.8.10 -y

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          # Add any other dependencies you need here
          python3-pip

        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Run my custom action
      run: echo "Hello from my Frist custom action!"
